project:
  type: book

book:

   title: "Powered by Linear Algebra"
   subtitle: "The central role of matrices and vector spaces in Data Science"
   author: 
     - name: Norman Matloff
       email: nsmatloff@ucdavis.edu
       affiliations:
         - name: University of California, Davis
   date: today

   cover-image: Projections.png
   
   chapters:
     - index.qmd
     - preface.qmd
     - Ch1.qmd
     - Ch2.qmd
     - Ch2a.qmd
     - Ch3.qmd
     - Ch4.qmd
     - Ch5a.qmd
     - Ch5b.qmd
     - Ch5c.qmd
     - Ch6a.qmd
     - Ch6b.qmd
     - Ch6c.qmd
     - Ch6d.qmd
     - Ch8a.qmd
   
format:
  html:
     toc: true
     toc-depth: 3
     toc-title: Contents
     number-sections: true
     fig_caption: no
     fig_numbers: no
  pdf:
     toc: true  
     number-sections: true      
     fig_caption: no
     fig_numbers: no
execute:
   warning: false
   message: false


