project:
  type: book

book:

   title: "Wacky Linear Algebra"
   subtitle: "A most unconventional approach"
   author: 
     - Norman Matloff
   date: "11/27/2024"
   
   chapters:
     - index.qmd
     - Ch1.qmd
   
format:
  pdf:
     toc: true
     number-sections: true
     fig_caption: no
     fig_numbers: no
  html:
     toc: true
     number-sections: true
     fig_caption: no
     fig_numbers: no
    


