project:
  type: book
  output-dir: docs

book:
   title: "Powered by Linear Algebra"
   subtitle: "The central role of matrices and vector spaces in Data Science"
   author: 
     - name: Norman Matloff
       email: nsmatloff@ucdavis.edu
       affiliations:
         - name: University of California, Davis
   date: today
   
   chapters:
     - index.qmd
     - preface.qmd
     - Ch1.qmd
     - Ch2.qmd
     - Ch2a.qmd
     - Ch3.qmd
     - Ch3a.qmd
     - Ch4.qmd
     - Ch5a.qmd
     - Ch5b.qmd
     - Projections.qmd
     - Ch5bb.qmd
     - Ch5c.qmd
     - Ch6a.qmd
     - Ch6b.qmd
     - Ch6c.qmd
     - Ch6d.qmd
     - Ch8a.qmd
   
format:
  html:
     toc: true
     toc-depth: 3
     toc-title: Contents
     number-sections: true
     fig_caption: no
     fig_numbers: no
     embed-resources: true
  pdf:
     toc: true  
     number-sections: true      
     fig_caption: no
     fig_numbers: no
     header-includes: |
      \titlehead{\includegraphics[width=2in]{Projections.png}}

execute:
   warning: false
   message: false


